# Generated by Django 5.2.3 on 2025-06-24 18:03

from django.db import migrations

def insert_migrations(apps, schema_editor):
    Currency = apps.get_model('tradingbotweb', 'Currency')
    Currency(symbol='USD', usd_value=1.40).save()
    Currency(symbol='EUR', usd_value=1.10).save()
    Currency(symbol='GBP', usd_value=1.20).save()
    Currency(symbol='JPY', usd_value=0.0075).save()
    Currency(symbol='BTC', usd_value=30000.00).save()
    Currency(symbol='ETH', usd_value=2000.00).save()
             
class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_migrations)
    ]
