# Generated by Django 5.2.3 on 2025-06-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0003_currencyhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destination_curency',
            new_name='destination_currency',
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_porfolio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingbotweb.currency')),
            ],
        ),
    ]
