# Generated by Django 5.2.3 on 2025-06-24 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbotweb', '0004_rename_destination_curency_transaction_destination_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencybalance',
            name='share_porfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
